import Head from "next/head";

import { Web3Button } from "@web3modal/react";
import {
  useDisconnect,
  usePrepareContractWrite,
  useContractWrite,
} from "wagmi";
import { useWeb3ModalTheme } from "@web3modal/react";
import w3mv2ProxyContractABI from "../abi/w3mv2ProxyContractABI.json";
import Image from "next/image";
import { ethers } from "ethers";

export default function Home() {
  // const { address } = useAccount();
  const { theme, setTheme } = useWeb3ModalTheme();
  const { disconnect } = useDisconnect();

  setTheme({ themeColor: "blackWhite" });

  // Use contract read
  // const { data: readTutorialContract, isError } = useContractRead({
  //   address: "0x398e3493d980533bB77Ff7e26A8C6C80f6D52C1C",
  //   abi: w3mv2ProxyContractABI,
  //   functionName: "name",
  // });

  const { config } = usePrepareContractWrite({
    address: "0x398e3493d980533bB77Ff7e26A8C6C80f6D52C1C",
    abi: w3mv2ProxyContractABI,
    functionName: "purchase",
    args: [1],
    overrides: { value: ethers.utils.parseEther("0.001") },
  });

  const { data, write: mintNFT } = useContractWrite(config);

  return (
    <>
      <Head>
        <title>Web3ModalV2 Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          marginTop: "2em",
          marginRight: "2em",
          display: "flex",
          justifyContent: "flex-end",
          paddingRight: "1em",
        }}
      >
        <Web3Button />
      </div>
      <main
        style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Image
          src="/gateway.jpg"
          style={{
            border: "1px solid grey",
            marginTop: "3em",
            borderRadius: "1em",
          }}
          width={400}
          height={400}
          alt="gateway"
        />

        <div
          style={{
            display: "flex",
            flexDirection: "column",
            marginTop: "2em",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <div>
            <h1>Web3ModalV2 Tutorial</h1>
          </div>

          <button
            onClick={() => mintNFT?.()}
            style={{
              marginTop: "1em",
              color: "black",
              borderRadius: 16,
              backgroundColor: "white",
              height: 50,
              width: 100,
            }}
          >
            Mint
          </button>
        </div>
      </main>
    </>
  );
}
